In [1]:
import numpy as np
my_list=['1','2','3','4','5']
arr=np.array(my_list)
type(arr)  #to check datatype

numpy.ndarray

In [2]:
print(arr)


['1' '2' '3' '4' '5']


In [3]:
arr.shape #tells how many rows or columns the data has 

(5,)

In [4]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[3,4,5,6,7]
arr=np.array([my_list1,my_list2,my_list3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [5]:
arr.shape


(3, 5)

In [6]:
arr.reshape(5,3) #5 rows 3 columns

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

NUMPY is a general purpose array processing package. Used to create multi dimensional arrays. It has binding of c/c++ libraries so its very quick. 
while python lists can contain diff data types, array has same data types
array operations are very fast 


In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[3]


4

In [9]:
arr=np.array([my_list1,my_list2,my_list3])
arr[:,:] # picks all elements from left and right

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [10]:
arr[0:2,0:2] #1,2 row :1,2, column

array([[1, 2],
       [2, 3]])

In [11]:
arr[3:5,1:2]

array([], shape=(0, 1), dtype=int32)

In [12]:
arr[3:4,1:2]

array([], shape=(0, 1), dtype=int32)

In [13]:
arr[1:,3:]

array([[5, 6],
       [6, 7]])

In [14]:
arr[1:,2:4]

array([[4, 5],
       [5, 6]])

In [15]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [16]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr=np.arange(0,2,10)
arr

array([0])

In [18]:
arr=np.arange(0,10,step=2) #step of 2
arr

array([0, 2, 4, 6, 8])

In [19]:
np.linspace(1,10,50)   #gives 50 points between 1 and 10

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [20]:
#copy function and broadcasting 
arr[3:]=100
arr
#replaces all values from 3rd index as 100

array([  0,   2,   4, 100, 100])

In [22]:
arr1=arr
arr1[3:]=500
arr1

array([  0,   2,   4, 500, 500])

In [23]:
arr

array([  0,   2,   4, 500, 500])

In [24]:
arr1=arr.copy()
print(arr)
arr1[3:]=1000
print(arr1) # new memory for arr1 is created hence change in arr1 wont affect arr

[  0   2   4 500 500]
[   0    2    4 1000 1000]


In [26]:
#conditions very useful in exploratory data analysis
val=2
arr<2

array([ True, False, False, False, False])

In [27]:
arr*2

array([   0,    4,    8, 1000, 1000])

In [28]:
arr/2

array([  0.,   1.,   2., 250., 250.])

In [29]:
arr[arr<2]

array([0])

In [30]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [31]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.random.rand(3,3) #random values

array([[0.16278315, 0.07599477, 0.55299715],
       [0.71779797, 0.67639144, 0.89756591],
       [0.15724025, 0.44230621, 0.65191441]])

In [33]:
np.random.randn(4,4) #based on standard normal dist

array([[ 0.51712643,  0.85403652,  0.46781966,  0.1330747 ],
       [-0.3253191 , -0.18946191,  1.24580779, -0.00592024],
       [-0.7194489 , -1.79428914, -0.8936578 ,  1.08501571],
       [ 0.56704727, -0.1827894 , -1.39982395, -0.59163873]])

In [36]:
#PRACTICE
import numpy as np 
mylist=[1,2,3,4,5]
arr=np.array(mylist)
arr
print(arr)

[1 2 3 4 5]


In [37]:
type(arr)

numpy.ndarray

In [39]:
arr.shape

(5,)